=== kevanescence/TDDD43/public_html/lab1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.0" elementFormDefault="qualified">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="experts_list" type="expert_list_type">
                    <!--Specify that all experts must have a different email -->
                    <xs:unique name="expertEmailUnique">
                        <xs:selector xpath="expert" />
                        <xs:field xpath="email" />
                    </xs:unique>
                </xs:element>
                <xs:element name="topics_list" type="topics_list_type">
                    <!-- Specify that all topics must have a different name -->
                    <xs:unique name="topicNameUnique">
                        <xs:selector xpath="topic" />
                        <xs:field xpath="name" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- Define the key on the experts -->
        <xs:key name="expertKey">
            <xs:selector xpath="experts_list/expert" />
            <xs:field xpath="@id" />
        </xs:key>                        
        <!-- Expert recommendation constraints -->
        <xs:keyref name="fk_experts_recommends" refer="expertKey">
            <xs:selector xpath="experts_list/expert" />
            <xs:field xpath="recommands" />
        </xs:keyref>
        <!-- Define the key on the topics -->
        <xs:key name="topicKey">
            <xs:selector xpath="topics_list/topic" />
            <xs:field xpath="@id" />
        </xs:key>
        <!-- The organisator must exist -->
        <xs:keyref name="fk_topics_experts" refer="expertKey">
            <xs:selector xpath="topics_list/topic" />
            <xs:field xpath="organisator" />
        </xs:keyref>
        <!-- Subtopic constraint -->
        <xs:keyref name="fk_subtopics" refer="topicKey">
            <xs:selector xpath="topics_list/topic" />
            <xs:field xpath="subtopic" />
        </xs:keyref>
    </xs:element>
    
    <!-- Define the expert_list type -->
    <xs:complexType name="expert_list_type">
        <xs:sequence>
            <xs:element name="expert" type="expert_type" 
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>                   
    </xs:complexType>
    <!-- Define the expert type -->
    <xs:complexType name="expert_type">
        <xs:sequence>            
            <xs:element name="name" type="xs:string"/> 
            <xs:element name="email" type="xs:string"/>
            <xs:element name="recommands" type="xs:int"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>        
        <xs:attribute name="id" type="xs:int" use="required" />        
    </xs:complexType>
    
    <!-- Define a list of topics -->
    <xs:complexType name="topics_list_type">
        <xs:sequence>
            <xs:element name="topic" type="topic_type"
                        minOccurs="0" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>        
    </xs:complexType>
    
    <!-- Define a topic -->
    <xs:complexType name="topic_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="organisator" type="xs:int"/>
            <xs:element name="subtopic" type="xs:int"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== kevanescence/TDDD43/public_html/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="lab1.xsd">
    <experts_list>
        <expert id="3">
            <name>JJ</name>
            <email>blablablubl</email>
             <recommandation>
                <recommands>4</recommands>
            </recommandation>
        </expert>
        <expert id="4">
            <name>tutu</name>
            <email>blabla</email>
            <recommandation>
                <recommanded>3</recommanded>
            </recommandation>
            <recommandation>
                <recommands>5</recommands>
            </recommandation>
        </expert>
        <expert id="5">
            <name>tutu</name>
            <email>blablablbulu</email>
        </expert>
    </experts_list>
    <topics_list>
        <topic id="1">
            <name>DB</name>
            <organisator>3</organisator>
            <subtopic>3</subtopic>
        </topic>
        <topic id="2">
            <name>CS</name>
            <organisator>3</organisator>
            <subtopic>1</subtopic>
            <!--<subtopic>3</subtopic>-->
        </topic>
        <topic id="3">
            <name>SQL</name>
            <organisator>4</organisator>            
        </topic>
    </topics_list>
</root>
